services:
  redisdb:
    container_name: redisdb
    image: redis
    ports:
      - "6379:6379"
    networks:
      - PrviNetwork
    volumes:
      - redis_data:/data

  nike_shopping:
    image: thien19012004/nike_shopping:latest
    container_name: nike_shopping
    ports:
      - "7000:5000"
    environment:
      - PORT=5000
      - DB_URI=mongodb+srv://ducthien19012004:thien19012004@cluster0.jafns.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=my-ultra-secure-and-ultra-long-secret
      - EMAIL_USER=phantaihbl9102018@gmail.com
      - EMAIL_PASSWORD=agcsccqhrzjwmnin
      - GOOGLE_CLIENT_ID=301795652850-793ushgv368si82cvtimgje7sh4g2tra.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - CLOUDINARY_CLOUD_NAME=dveziesz4
      - CLOUDINARY_API_KEY=123648789834145
      - CLOUDINARY_API_SECRET=rCi97XiatpKcPxvBMhiFwvq2UyU
    restart: always
    networks:
      - PrviNetwork
    labels:
      - "traefik.http.routers.nike_shopping-secure.rule=Host(`nikeshopping.lptdevops.website`)"
      - "traefik.http.routers.nike_shopping-secure.entrypoints=websecure"
      - "traefik.http.routers.nike_shopping-secure.tls=true"
      - "traefik.http.routers.nike_shopping-secure.tls.certresolver=leresolver"

      - "traefik.http.routers.nike_shopping.rule=Host(`nikeshopping.lptdevops.website`)"
      - "traefik.http.routers.nike_shopping.entrypoints=web"
      - "traefik.http.routers.nike_shopping.middlewares=redirect-to-https"

      - "traefik.http.services.nike_shopping.loadbalancer.server.port=5000"

networks:
  PrviNetwork:
    external: true

volumes:
  redis_data: